### ISSUE TITLE
域名添加成功后，在域名列表可以看到域名，但是解析记录里面是空的。

### ISSUE THREAD

**Issue by putianhui** [xiaoxin1992/bind-pod#1]
域名添加成功后，在域名列表可以看到域名，但是解析记录里面是空的。
直接在解析记录里面添加一条新记录，客户端测试新记录是添加成功的，就是记录列表里面看不到是为什么？
![image](https://user-images.githubusercontent.com/68322685/141229953-1918b1ec-fa01-44c0-ae84-a957a773a334.png)
![image](https://user-images.githubusercontent.com/68322685/141230049-7c5aa81c-df07-487b-b423-4f7fdb46fef5.png)

```bash
2021-11-11 10:59:03,815 - WARNING - Not Found: /agent/resolve/list/putianhui-local.cn/
[11/Nov/2021 10:59:03] "GET /agent/resolve/list/putianhui-local.cn/?size=10&page=1&name= HTTP/1.1" 404 77
[11/Nov/2021 10:59:06] "GET /agent/user/info/ HTTP/1.1" 200 45
2021-11-11 10:59:06,768 - WARNING - Not Found: /agent/resolve/list/putianhui-local.cn/
[11/Nov/2021 10:59:06] "GET /agent/resolve/list/putianhui-local.cn/?size=10&page=1&name= HTTP/1.1" 404 77
[11/Nov/2021 10:59:10] "POST /login/ HTTP/1.1" 200 300
[11/Nov/2021 10:59:11] "GET /agent/domain/?size=10&page=1&domain= HTTP/1.1" 200 222
2021-11-11 10:59:16,159 - WARNING - Not Found: /agent/resolve/list/putianhui-local.cn/
[11/Nov/2021 10:59:16] "GET /agent/resolve/list/putianhui-local.cn/?size=10&page=1&name= HTTP/1.1" 404 77
```

**Comment by xiaoxin1992** [comment]
我测试没有问题
下面是我的/etc/named.conf配置，您可以参考下
//
// named.conf
//
// Provided by Red Hat bind package to configure the ISC BIND named(8) DNS
// server as a caching only nameserver (as a localhost DNS resolver only).
//
// See /usr/share/doc/bind*/sample/ for example named configuration files.
//
// See the BIND Administrator's Reference Manual (ARM) for details about the
// configuration located in /usr/share/doc/bind-{version}/Bv9ARM.html

options {
	listen-on port 53 { 127.0.0.1; };
	listen-on-v6 port 53 { ::1; };
	directory 	"/var/named";
	dump-file 	"/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	recursing-file  "/var/named/data/named.recursing";
	secroots-file   "/var/named/data/named.secroots";
	allow-query     { localhost; };

	/*
	 - If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
	 - If you are building a RECURSIVE (caching) DNS server, you need to enable
	   recursion.
	 - If your recursive DNS server has a public IP address, you MUST enable access
	   control to limit queries to your legitimate users. Failing to do so will
	   cause your server to become part of large scale DNS amplification
	   attacks. Implementing BCP38 within your network would greatly
	   reduce such attack surface
	*/
	recursion yes;

	dnssec-enable yes;
	dnssec-validation yes;

	/* Path to ISC DLV key */
	bindkeys-file "/etc/named.root.key";

	managed-keys-directory "/var/named/dynamic";

	pid-file "/run/named/named.pid";
	session-keyfile "/run/named/session.key";
};

logging {
        channel default_debug {
                file "data/named.run";
                severity dynamic;
        };
};

key "rndc-key" {
	algorithm hmac-md5;
	secret "8XhahdtLNWhIfpDQjdhvOQ==";
};

controls {
	    inet 127.0.0.1 port 953
	    allow { any; } keys { "rndc-key"; };
};

# davidddns. IN KEY 0 3 157 hpvLkDRozTdGSPRPB9s5/A==
key "davidddns" {
	algorithm hmac-md5;
	secret "hpvLkDRozTdGSPRPB9s5/A==";
};



zone "." IN {
	type hint;
	file "named.ca";
};

zone "xiaoxin.com" IN {
    type master;
    file "xiaoxin.com.zone";
    allow-update { key davidddns; };
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";

/var/named/xiaoxin.com.zone 文件配置
$ORIGIN .
$TTL 86400	; 1 day
xiaoxin.com		IN SOA	xiaoxin.com. rname.invalid. (
				83         ; serial
				86400      ; refresh (1 day)
				3600       ; retry (1 hour)
				604800     ; expire (1 week)
				10800      ; minimum (3 hours)
				)
			NS	xiaoxin.com.
			A	127.0.0.1
$TTL 300	; 5 minutes
			MX	20 mail.www.com.
			MX	20 mail.baidu.com.
			MX	20 com.cn.
			MX	20 mail.baidu2.com.
$TTL 86400	; 1 day
			AAAA	::1
$ORIGIN xiaoxin.com.
$TTL 600	; 10 minutes
ces1			A	192.168.100.240
test			A	10.10.10.10
			A	10.1.1.2
www			A	192.168.1.1
xiaoxin			A	192.168.100.245
			A	192.168.100.200
			A	192.168.100.202
xiaoxin121		A	192.168.100.240



服务端配置文件
config/bindpod.json
{
  "dns": {
    "server": "127.0.0.1",
    "port": 53,
    "key": "davidddns",
    "secret": "hpvLkDRozTdGSPRPB9s5/A=="
  },
  "database": {
    "sqlite": {
      "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "./db.sqlite3"
      }
    },
    "mysql": {
      "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "mysql_database",
        "USER": "USER",
        "PASSWORD": "PASSWORD",
        "HOST": "127.0.0.1",
        "PORT": "3306",
        "OPTIONS": {
          "init_command": "SET sql_mode='STRICT_TRANS_TABLES'"
        }
      }
    },
    "select": "sqlite"
  }
}
服务端启动:
python3 manage.py makemigrations
/python3 manage.py migrate
python3 manage.py runserver 0.0.0.0:8080

前端启动
npm run serve


把下面配置替换成你自己的
key "davidddns" {
	algorithm hmac-md5;
	secret "hpvLkDRozTdGSPRPB9s5/A==";
};


![image](https://user-images.githubusercontent.com/11681161/141232991-b5a57b6d-4a46-40a0-b536-35b1a903fb0f.png)

**Comment by putianhui** [comment]
老哥，我听朋友说这个项目url正则匹配没有去匹配带'-'的域名？  所以导致我的域名带了- 无法解析

**Comment by putianhui** [comment]
文件 `agent/views_lib/resolve.py`的116行

原来
```bash
 @action(detail=False, methods=["GET"], url_path='list/(?P<domain>[a-z.]+)')
```
改后
```bash
 @action(detail=False, methods=["GET"], url_path='list/(?P<domain>[a-z.-]+)')
```

![image](https://user-images.githubusercontent.com/68322685/141233306-dc791593-05dd-4f1e-90a2-3e2ff80589f7.png)

**Comment by xiaoxin1992** [comment]
支持正则[-a-zA-Z0-9.]+   拉取新的后段代码生效
