### ISSUE TITLE
zone创建问题咨询

### ISSUE THREAD

**Issue by huadianer** [xiaoxin1992/bind-pod#2]
Hi 大佬，

我代码拉下来之后，调试可以用了，但是，关于zone文件创建，我目前是手动在本机/tmp/目录下创建

![image](https://user-images.githubusercontent.com/25215114/152953094-5861cda5-6e93-4721-83ca-38391c54ecb0.png)

然后，再在bind9机器上面配置相关文件,然后还得重启下才能使用
![image](https://user-images.githubusercontent.com/25215114/152953456-5e3cb3bc-a1f6-4374-8216-338ff29b5546.png)
![image](https://user-images.githubusercontent.com/25215114/152953649-49b98d39-3a4c-4897-9e56-4e8a1b23b98e.png)

这样的创建zone的方式，我感觉我可能弄的有点麻烦，有比较简便的，或者相关的工具包么？

BR
Robin

**Comment by xiaoxin1992** [comment]
这个目前增加区域文件功能平台还没有接管， 对于新增的区域文件配置好以后可以使用rndc reconfig 进行动态加载， 您也可以对平台进行二次开发来增加zone文件生成和加载配置功能

**Comment by huadianer** [comment]
hi @xiaoxin1992 

好的，我这边来研究看看


BR
Robin
